# Generated by Django 2.1 on 2020-10-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201015_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cert',
            name='deprt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cert',
            name='nomOrg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cert',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cert',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
